// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasteSegregation.DataAccess;

#nullable disable

namespace WasteSegregation.DataAccess.Migrations
{
    [DbContext(typeof(WasteSegregationContext))]
    [Migration("20220707190621_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WasteSegregation.DataAccess.Entities.WasteBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlueBag")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("BrownBag")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("GreenBag")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("YellowBag")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WasteBags");
                });
#pragma warning restore 612, 618
        }
    }
}
