global using System;
global using System.Collections.Generic;
global using AutoMapper;
global using WasteSegregation.Application.Dto;
global using WasteSegregation.Domain.Entities;
global using System.Threading.Tasks;
global using WasteSegregation.Application.Interfaces;
global using WasteSegregation.Domain.Interfaces;
global using Microsoft.Extensions.Logging;
